# Generated by Django 5.1.7 on 2025-06-07 15:33

import datetime
import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name="Student's full name")),
                ('registration_number', models.CharField(max_length=6, unique=True, verbose_name="Student's registration")),
                ('phone_number', models.CharField(max_length=15, validators=[utils.validators.phone_validator], verbose_name="Student's phone number (XX) 9XXXX-XXXX")),
                ('email', models.EmailField(max_length=100, verbose_name="Student's email")),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[utils.validators.cpf_validator], verbose_name="Student's CPF")),
                ('birthday', models.DateField(max_length=10)),
                ('address', models.CharField(max_length=100, validators=[utils.validators.cep_validator])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 53, 399249), editable=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.group', verbose_name="Student's group")),
                ('itinerary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.itinerary', verbose_name="Student's itinerary")),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 53, 401955), editable=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_list', to='students.student', verbose_name="Student's name")),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name="Guardian's full name")),
                ('phone_number', models.CharField(max_length=15, validators=[utils.validators.phone_validator], verbose_name="Guardian's phone number (XX) 9XXXX-XXXX")),
                ('email', models.EmailField(max_length=100, verbose_name="Guardian's email")),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[utils.validators.cpf_validator], verbose_name="Guardian's CPF")),
                ('birthday', models.DateField(max_length=10)),
                ('address', models.CharField(max_length=100, validators=[utils.validators.cep_validator])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 53, 400044), editable=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_student', to='students.student', verbose_name="Guardian's student")),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('values', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 53, 401410), editable=False)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.subject', verbose_name="Grade's Subject")),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name="Student's name")),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 53, 400590), editable=False)),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrac', to='students.guardian', verbose_name="Guardian's name")),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='students.student', verbose_name="Student's name")),
            ],
        ),
    ]
