# Generated by Django 5.1.7 on 2025-06-07 15:00

import datetime
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 29, 268854), editable=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 29, 269669), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[utils.validators.cpf_validator], verbose_name="Guardian's CPF"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 29, 268399), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 29, 270247), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[utils.validators.cpf_validator], verbose_name="Student's CPF"),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 29, 267669), editable=False),
        ),
    ]
