# Generated by Django 5.1.7 on 2025-06-07 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='values',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 14, 17, 375096), editable=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 14, 17, 375917), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 14, 17, 374577), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 14, 17, 376455), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 14, 17, 373768), editable=False),
        ),
    ]
