# Generated by Django 5.1.7 on 2025-06-07 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_guardian_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 652424), editable=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 653420), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 651948), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 653988), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 651086), editable=False),
        ),
    ]
