# Generated by Django 5.1.7 on 2025-06-07 16:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_book_created_at_alter_group_created_at_and_more'),
        ('students', '0002_rename_values_grades_value_alter_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 18, 44, 907549), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 18, 44, 907059), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 18, 44, 908870), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 18, 44, 906267), editable=False),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('value', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 18, 44, 908335), editable=False)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='students.student', verbose_name="Student's name")),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='school.subject', verbose_name="Grade's Subject")),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
