# Generated by Django 5.1.7 on 2025-06-14 17:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_book_created_at_alter_book_tenant_and_more'),
        ('students', '0003_alter_contract_created_at_alter_grade_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 18, 587447), editable=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='students.guardian', verbose_name="Guardian's name"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='students.student', verbose_name="Student's name"),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 18, 588480), editable=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='students.student', verbose_name="Student's name"),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='school.subject', verbose_name="Grade's Subject"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 18, 586869), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian', to='students.student', verbose_name="Guardian's student"),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 18, 589165), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence', to='students.student', verbose_name="Student's name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 18, 586033), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='school.group', verbose_name="Student's group"),
        ),
        migrations.AlterField(
            model_name='student',
            name='itinerary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='school.itinerary', verbose_name="Student's itinerary"),
        ),
    ]
