# Generated by Django 5.1.7 on 2025-06-07 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_contract_created_at_alter_grade_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='bimester',
            field=models.CharField(choices=[('1B', '1º Bimestre'), ('2B', '2º Bimestre'), ('3B', '3º Bimestre'), ('4B', '4º Bimestre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 37, 15, 825482), editable=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 37, 15, 826407), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 37, 15, 824966), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 37, 15, 826987), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 37, 15, 824139), editable=False),
        ),
    ]
