# Generated by Django 5.1.7 on 2025-06-15 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_contract_created_at_alter_grade_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='itinerary',
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 21, 22, 47, 444207), editable=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 21, 22, 47, 445079), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 21, 22, 47, 443715), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 21, 22, 47, 445625), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 21, 22, 47, 442948), editable=False),
        ),
    ]
