# Generated by Django 5.1.7 on 2025-06-15 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_contract_created_at_alter_grade_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 989389), editable=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 990247), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 988894), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 990827), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 988130), editable=False),
        ),
    ]
