# Generated by Django 5.1.7 on 2025-08-06 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_contract_created_at_alter_grade_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 18, 39, 6, 651722), editable=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 18, 39, 6, 652238), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 18, 39, 6, 651198), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 18, 39, 6, 652804), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 18, 39, 6, 650531), editable=False),
        ),
    ]
