# Generated by Django 5.1.7 on 2025-11-11 08:15

import django.db.models.deletion
import django.utils.timezone
import utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Nome completo",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Nome curto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "db_table": "school_group",
            },
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Nome completo",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Nome curto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerário",
                "verbose_name_plural": "Itinerários",
                "db_table": "school_itinerary",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Nome curto",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name="Nome completo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matéria",
                "verbose_name_plural": "Matérias",
                "db_table": "school_subject",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=utils.date.get_current_year, verbose_name="Ano"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        default=utils.date.get_today, verbose_name="Data de matrícula"
                    ),
                ),
                (
                    "is_reenrollment",
                    models.BooleanField(default=False, verbose_name="É rematrícula"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.student",
                        verbose_name="Estudante",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.group",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "db_table": "students_enrollment",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="itinerary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group",
                to="academics.itinerary",
                verbose_name="Itinerário",
            ),
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=utils.date.get_today, verbose_name="Data"),
                ),
                ("presence", models.BooleanField(verbose_name="Presença")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presence",
                        to="students.student",
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença",
                "verbose_name_plural": "Presenças",
                "db_table": "students_presence",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.IntegerField(null=True, verbose_name="Horário (1 a 6)"),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Segunda"),
                            (2, "Terça"),
                            (3, "Quarta"),
                            (4, "Quinta"),
                            (5, "Sexta"),
                            (6, "Sábado"),
                        ],
                        null=True,
                        verbose_name="Dia",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="academics.group",
                        verbose_name="Turma",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="students.professor",
                        verbose_name="Professor",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="academics.subject",
                        verbose_name="Disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "db_table": "school_lesson",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=utils.date.get_current_year,
                        null=True,
                        verbose_name="Ano",
                    ),
                ),
                (
                    "bimester",
                    models.CharField(
                        choices=[
                            ("1B", "1º Bimestre"),
                            ("2B", "2º Bimestre"),
                            ("3B", "3º Bimestre"),
                            ("4B", "4º Bimestre"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Bimestre",
                    ),
                ),
                ("value", models.FloatField(null=True, verbose_name="Valor")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade",
                        to="students.student",
                        verbose_name="Estudante",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade",
                        to="academics.subject",
                        verbose_name="Matéria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "db_table": "students_grade",
            },
        ),
        migrations.CreateModel(
            name="WeeklyLessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(verbose_name="Início da semana")),
                (
                    "planning_content",
                    models.TextField(
                        help_text="Conteúdo programado para a semana",
                        verbose_name="Planejamento",
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True,
                        help_text="Objetivos de aprendizagem da semana",
                        null=True,
                        verbose_name="Objetivos",
                    ),
                ),
                (
                    "resources_needed",
                    models.TextField(
                        blank=True,
                        help_text="Materiais e recursos necessários",
                        null=True,
                        verbose_name="Recursos necessários",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_plans",
                        to="academics.lesson",
                        verbose_name="Aula",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_plans",
                        to="students.professor",
                        verbose_name="Professor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planejamento Semanal",
                "verbose_name_plural": "Planejamentos Semanais",
                "db_table": "school_weeklylessonplan",
                "ordering": ["-week_start_date"],
                "unique_together": {("lesson", "week_start_date")},
            },
        ),
    ]
