services:
  proxy:
    build: ./proxy
    container_name: test-school-secretary-proxy
    ports:
      - 8080:80
    volumes:
      - test_api_static:/vol/web/static/
      - test_api_media:/vol/web/media/
    env_file:
      - ./proxy/.env
    depends_on:
      api:
        condition: service_healthy
      app:
        condition: service_healthy
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    container_name: test-school-secretary-app
    volumes:
      - test_app_node_modules:/app/node_modules
      - test_app_next:/app/.next
    environment:
      - NODE_ENV=test
    env_file:
      - ./app/.env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - public
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "curl -sf http://localhost:3000/healthcheck || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    container_name: test-school-secretary-api
    volumes:
      - test_api_static:/vol/web/static/
      - test_api_media:/vol/web/media/
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public
      - private
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python /api/healthcheck.py"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    build: ./db
    container_name: test-school-secretary-db
    volumes:
      - test_db_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
    networks:
      - private
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  test_db_data:
  test_api_static:
  test_api_media:
  test_app_node_modules:
  test_app_next:
