# Generated by Django 5.1.7 on 2025-11-11 08:15

import django.db.models.deletion
import django.utils.timezone
import utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("COMPUTER", "Computador"),
                            ("BOOK", "Livro"),
                            ("EQUIPMENT", "Equipamento"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Disponível"),
                            ("IN_USE", "Em uso"),
                            ("MAINTENANCE", "Manutenção"),
                            ("UNAVAILABLE", "Indisponível"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
            },
        ),
        migrations.CreateModel(
            name="ResourceLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_date",
                    models.DateField(
                        default=utils.date.get_today, verbose_name="Data de empréstimo"
                    ),
                ),
                (
                    "return_date",
                    models.DateField(verbose_name="Data de devolução prevista"),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de devolução efetiva"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="resources.resource",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo de Recurso",
                "verbose_name_plural": "Empréstimos de Recursos",
            },
        ),
    ]
