# Generated by Django 5.1.7 on 2025-11-11 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceloan",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_loans",
                to="students.student",
                verbose_name="Estudante",
            ),
        ),
    ]
