# Generated by Django 5.1.7 on 2025-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Guardian's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="Guardian's last name")),
                ('registration_number_student', models.CharField(max_length=6, unique=True, verbose_name="Student's registration")),
                ('phone_number', models.CharField(max_length=15, verbose_name="Guardian's phone number (xx) xxxxx-xxxx")),
                ('email', models.EmailField(max_length=100, verbose_name="Guardian's email")),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField(max_length=25)),
                ('adress', models.CharField(max_length=100)),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Professor's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="Professor's last name")),
                ('phone_number', models.CharField(max_length=15, verbose_name="Professor's phone number (xx) xxxxx-xxxx")),
                ('email', models.EmailField(max_length=100, verbose_name="Professor's email")),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField(max_length=25)),
                ('adress', models.CharField(max_length=100)),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2)),
                ('test', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Student's first name")),
                ('last_name', models.CharField(max_length=50, verbose_name="Student's last name")),
                ('registration_number', models.CharField(max_length=6, unique=True, verbose_name="Student's registration")),
                ('phone_number', models.CharField(max_length=15, verbose_name="Student's phone number (xx) xxxxx-xxxx")),
                ('email', models.EmailField(max_length=100, verbose_name="Student's email")),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField(max_length=25)),
                ('adress', models.CharField(max_length=100)),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2)),
            ],
        ),
    ]
