# Generated by Django 5.1.7 on 2025-03-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='test',
        ),
    ]
