# Generated by Django 5.1.7 on 2025-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_professor_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='birthday',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='birthday',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(max_length=10),
        ),
    ]
