# Generated by Django 5.1.7 on 2025-04-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_guardian_birthday_alter_professor_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='class_choices',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='class_choices',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_choices',
        ),
        migrations.AlterField(
            model_name='guardian',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name="Guardian's first name"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name="Guardian's last name"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name="Professor's first name"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name="Professor's last name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name="Student's first name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name="Student's last name"),
        ),
        migrations.AddField(
            model_name='guardian',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_student', to='school.classes', verbose_name="Student's class"),
        ),
        migrations.AddField(
            model_name='professor',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_class', to='school.classes', verbose_name="Student's class"),
        ),
        migrations.AddField(
            model_name='student',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='school.classes', verbose_name="Student's class"),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_guardian', to='school.guardian', verbose_name="Guardian's name")),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_student', to='school.student', verbose_name="Student's name")),
            ],
        ),
    ]
