# Generated by Django 5.1.7 on 2025-04-02 14:37

import django.db.models.deletion
import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_classes_remove_guardian_class_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_choices', models.CharField(choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=50)),
                ('itinerary_choices', models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciencias da Natureza'), ('JG', 'Desenvolvimento de Jogos')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='guardian',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[school.models.cpf_validator]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[school.models.cpf_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[school.models.cpf_validator]),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_student', to='school.class', verbose_name="Student's class"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_class', to='school.class', verbose_name="Student's class"),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='school.class', verbose_name="Student's class"),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
