# Generated by Django 5.2 on 2025-04-08 22:54

import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_class_alter_guardian_cpf_alter_professor_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='adress',
            field=models.CharField(max_length=100, validators=[school.models.cep_validator]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='adress',
            field=models.CharField(max_length=100, validators=[school.models.cep_validator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='adress',
            field=models.CharField(max_length=100, validators=[school.models.cep_validator]),
        ),
    ]
