# Generated by Django 5.2 on 2025-04-08 23:02

import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_guardian_adress_alter_professor_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[school.models.cpf_validator], verbose_name="Guardian's CPF"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[school.models.cpf_validator], verbose_name="Professor's CPF"),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[school.models.cpf_validator], verbose_name="Student's CPF"),
        ),
    ]
