# Generated by Django 5.2 on 2025-04-09 12:24

import django.db.models.deletion
import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_guardian_cpf_alter_professor_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='class_choice',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='registration_number_student',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='guardian',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Guardian's full name"),
        ),
        migrations.AddField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_student', to='school.student', verbose_name="Guardian's student"),
        ),
        migrations.AddField(
            model_name='professor',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Professor's full name"),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Student's full name"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[school.validators.phone_validator], verbose_name="Guardian's phone number (XX) 9XXXX-XXXX"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[school.validators.phone_validator], verbose_name="Professor's phone number (XX) 9XXXX-XXXX"),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[school.validators.phone_validator], verbose_name="Student's phone number (XX) 9XXXX-XXXX"),
        ),
    ]
