# Generated by Django 5.1.7 on 2025-04-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_guardian_class_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.JSONField(null=True, verbose_name='JSON Values of Grades')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_student', to='school.student', verbose_name="Student's name")),
            ],
        ),
    ]
