# Generated by Django 5.1.7 on 2025-05-14 11:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='bimester',
            field=models.CharField(choices=[('1B', '1° Bimester'), ('2B', '2° Bimester'), ('3B', '3° Bimester'), ('4B', '4° Bimester')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 8, 9, 1, 891917)),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletin', to='school.student', verbose_name="Student's name"),
        ),
    ]
