# Generated by Django 5.1.7 on 2025-05-14 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_bulletin_bimester_alter_bulletin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 8, 28, 42, 660928)),
        ),
    ]
