# Generated by Django 5.1.7 on 2025-05-14 12:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_remove_bulletin_presence_alter_bulletin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 9, 42, 54, 828201)),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.JSONField()),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='school.professor', verbose_name="Professor's name")),
            ],
        ),
    ]
