# Generated by Django 5.1.7 on 2025-05-21 14:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_rename_adress_guardian_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('1F', '1° Ano do Fundamental'), ('2F', '2° Ano do Fundamental'), ('3F', '3° Ano do Fundamental'), ('4F', '4° Ano do Fundamental'), ('5F', '5° Ano do Fundamental'), ('6F', '6° Ano do Fundamental'), ('7F', '7° Ano do Fundamental'), ('8F', '8° Ano do Fundamental'), ('9F', '9° Ano do Fundamental'), ('1M', '1° Ano do Médio'), ('2M', '2° Ano do Médio'), ('3M', '3° Ano do Médio')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intinerary_name', models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciencias da Natureza'), ('JG', 'Desenvolvimento de Jogos')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('LING', 'Linguagens')], max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='class_choice',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_choice',
        ),
        migrations.AlterField(
            model_name='contract',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrac', to='school.guardian', verbose_name="Guardian's name"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='school.student', verbose_name="Student's name"),
        ),
        migrations.AddField(
            model_name='professor',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='school.group', verbose_name="Professor's Group"),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.group', verbose_name="Student's group"),
        ),
        migrations.AddField(
            model_name='student',
            name='itinerary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.itinerary', verbose_name="Student's itinerary"),
        ),
        migrations.CreateModel(
            name='SchoolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_record', to='school.student', verbose_name="Student's name")),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 5, 21, 11, 45, 50, 725803))),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.student', verbose_name="Student's name")),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.subject', verbose_name="Grade's Subject")),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='school.subject', verbose_name="Professor's Subject"),
        ),
        migrations.DeleteModel(
            name='Bulletin',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
