# Generated by Django 5.1.7 on 2025-06-04 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_book_created_at_alter_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={},
        ),
        migrations.RemoveField(
            model_name='grades',
            name='bimester',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='value',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.AddField(
            model_name='grades',
            name='values',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 16, 38, 264415)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 16, 38, 264415)),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 16, 38, 264415)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 16, 38, 264415)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 16, 38, 264415)),
        ),
    ]
