# Generated by Django 5.1.7 on 2025-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro nome do responsável')),
                ('last_name', models.CharField(max_length=50, verbose_name='Último nome do responsável')),
                ('registration_number_student', models.CharField(max_length=6, unique=True, verbose_name='Matrícula do aluno')),
                ('phone_number', models.CharField(max_length=15, verbose_name='N° do celular do responsável (xx) xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do responsável')),
                ('adress', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField()),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro nome do Professor')),
                ('last_name', models.CharField(max_length=50, verbose_name='Último nome do Professor')),
                ('phone_number', models.CharField(max_length=15, verbose_name='N° do celular do Professor (xx) xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do Professor')),
                ('adress', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField()),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro nome do aluno')),
                ('last_name', models.CharField(max_length=50, verbose_name='Último nome do aluno')),
                ('registration_number', models.CharField(max_length=6, unique=True, verbose_name='Matrícula do aluno')),
                ('phone_number', models.CharField(max_length=15, verbose_name='N° do celular do aluno (xx) xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do aluno')),
                ('adress', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birthday', models.DateField()),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2)),
            ],
        ),
    ]
