# Generated by Django 5.1.7 on 2025-03-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=models.EmailField(max_length=100, verbose_name="Guardian's email"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Guardian's first name"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name="Guardian's last name"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name="Guardian's phone number (xx) xxxxx-xxxx"),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='registration_number_student',
            field=models.CharField(max_length=6, unique=True, verbose_name="Student's registration"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=100, verbose_name="Professor's Email"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Professor's first name"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name="Professor's last name"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name="Professor's phone number (xx) xxxxx-xxxx"),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, verbose_name="Student's email"),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Student's first name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name="Student's last name"),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name="Student's phone number (xx) xxxxx-xxxx"),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=6, unique=True, verbose_name="Student's registration"),
        ),
    ]
