FROM node:22.18.0-alpine

RUN apk add --no-cache bash curl libc6-compat

WORKDIR /app

COPY package*.json tsconfig*.json ./
RUN npm ci

COPY . .

RUN npm run build

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["npm", "start"]