FROM node:22.18.0-alpine

RUN apk add --no-cache curl bash

WORKDIR /app

COPY package*.json tsconfig*.json ./

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", ".next/standalone/server.js"]
