# Generated by Django 5.1.7 on 2025-06-07 15:33

import datetime
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 52, 886973), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('1F', '1° Ano do Fundamental'), ('2F', '2° Ano do Fundamental'), ('3F', '3° Ano do Fundamental'), ('4F', '4° Ano do Fundamental'), ('5F', '5° Ano do Fundamental'), ('6F', '6° Ano do Fundamental'), ('7F', '7° Ano do Fundamental'), ('8F', '8° Ano do Fundamental'), ('9F', '9° Ano do Fundamental'), ('1M', '1° Ano do Médio'), ('2M', '2° Ano do Médio'), ('3M', '3° Ano do Médio')], max_length=40)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 52, 885410), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_name', models.CharField(choices=[('DS', 'Desenvolvimento de Sistemas'), ('CN', 'Ciencias da Natureza'), ('JG', 'Desenvolvimento de Jogos')], max_length=40)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 52, 885030), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name="Professor's full name")),
                ('phone_number', models.CharField(max_length=15, validators=[utils.validators.phone_validator], verbose_name="Professor's phone number (XX) 9XXXX-XXXX")),
                ('email', models.EmailField(max_length=100, verbose_name="Professor's email")),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[utils.validators.cpf_validator], verbose_name="Professor's CPF")),
                ('birthday', models.DateField(max_length=10)),
                ('address', models.CharField(max_length=100, validators=[utils.validators.cep_validator])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 52, 885921), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 52, 887424), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 52, 886503), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('CH', 'Ciências Humanas'), ('CN', 'Ciências da Natureza'), ('MAT', 'Matemática'), ('LING', 'Linguagens')], max_length=40)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 33, 52, 884661), editable=False)),
            ],
        ),
    ]
