# Generated by Django 5.1.7 on 2025-06-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alugated_book', to='students.student', verbose_name="Tenant's name"),
        ),
        migrations.AddField(
            model_name='professor',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='school.group', verbose_name="Professor's Group"),
        ),
        migrations.AddField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='school.professor', verbose_name="Professor's name"),
        ),
        migrations.AddField(
            model_name='schoolrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_record', to='students.student', verbose_name="Student's name"),
        ),
        migrations.AddField(
            model_name='professor',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='school.subject', verbose_name="Professor's Subject"),
        ),
    ]
