# Generated by Django 5.1.7 on 2025-06-07 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 28, 751013), editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 28, 749438), editable=False),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 28, 749047), editable=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 28, 749950), editable=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 28, 751463), editable=False),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 28, 750556), editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 0, 28, 748676), editable=False),
        ),
    ]
