# Generated by Django 5.1.7 on 2025-06-07 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_book_created_at_alter_group_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 82178), editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 80617), editable=False),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 80161), editable=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 81145), editable=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 82667), editable=False),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 81740), editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 1, 55, 79762), editable=False),
        ),
    ]
