# Generated by Django 5.1.7 on 2025-06-07 15:05

import datetime
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_book_created_at_alter_group_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 5, 25, 833844), editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 5, 25, 832356), editable=False),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 5, 25, 831976), editable=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, validators=[utils.validators.cpf_validator], verbose_name="Professor's CPF"),
        ),
        migrations.AlterField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 5, 25, 832872), editable=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 5, 25, 834275), editable=False),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 5, 25, 833351), editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 12, 5, 25, 831585), editable=False),
        ),
    ]
