# Generated by Django 5.1.7 on 2025-05-14 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_class_options_remove_bulletin_create_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='bimester',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 8, 27, 31, 600717)),
        ),
    ]
