# Generated by Django 5.1.7 on 2025-08-06 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_lesson_group_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 9, 45, 24, 360017), editable=False),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 9, 45, 24, 358009), editable=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 9, 45, 24, 360017), editable=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], null=True, verbose_name='Dia da semana (0=Domingo, 6=Sábado)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(null=True, verbose_name='Horários (1 a 6)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 9, 45, 24, 358009), editable=False),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 9, 45, 24, 360017), editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 9, 45, 24, 358009), editable=False),
        ),
    ]
