# Generated by Django 5.1.7 on 2025-05-14 12:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_bulletin_presence_alter_book_author_alter_book_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='presence',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 9, 25, 44, 461609)),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.BooleanField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presence_list', to='school.student', verbose_name="Student's name")),
            ],
        ),
    ]
