# Generated by Django 5.1.7 on 2025-05-14 14:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_alter_bulletin_created_at_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 11, 17, 26, 674063)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_class', to='school.class', verbose_name="Professor's class"),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to='school.class', verbose_name="Student's class"),
        ),
    ]
