# Generated by Django 5.1.7 on 2025-05-21 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_group_itinerary_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='intinerary_name',
            new_name='itinerary_name',
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 11, 49, 35, 269116)),
        ),
    ]
