# Generated by Django 5.1.7 on 2025-05-21 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_rename_intinerary_name_itinerary_itinerary_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 6, 43, 78347)),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 6, 43, 76623)),
        ),
        migrations.AddField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 6, 43, 77249)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 6, 43, 78347)),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 6, 43, 76623)),
        ),
    ]
