# Generated by Django 5.1.7 on 2025-05-28 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_book_created_at_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='values',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 8, 34, 53, 166051)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 8, 34, 53, 166051)),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 8, 34, 53, 166051)),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 8, 34, 53, 166051)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 8, 34, 53, 166051)),
        ),
    ]
