# Generated by Django 5.1.7 on 2025-06-04 13:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_grades_values_alter_book_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='values',
        ),
        migrations.AddField(
            model_name='grades',
            name='bimester',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='value',
            field=models.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 10, 7, 56, 916648)),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 10, 7, 56, 910754)),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 10, 7, 56, 916139)),
        ),
        migrations.AlterField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.student', verbose_name="Student's name"),
        ),
        migrations.AlterField(
            model_name='grades',
            name='subject',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.subject', verbose_name="Grade's Subject"),
        ),
        migrations.AlterField(
            model_name='grades',
            name='year',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 10, 7, 56, 916648)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 10, 7, 56, 918658)),
        ),
    ]
