# Generated by Django 5.1.7 on 2025-06-04 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_itinerary_options_remove_grades_bimester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AddField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AddField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AlterField(
            model_name='grades',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 4, 11, 19, 45, 431872), editable=False),
        ),
    ]
