# Generated by Django 5.1.7 on 2025-11-11 08:15

import django.utils.timezone
import utils.date
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=utils.date.get_current_year, verbose_name="Ano"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[utils.validators.cpf_validator],
                        verbose_name="CPF",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Data de nascimento")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validators.phone_validator],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        validators=[utils.validators.cep_validator],
                        verbose_name="CEP",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[utils.validators.cpf_validator],
                        verbose_name="CPF",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Data de nascimento")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validators.phone_validator],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        validators=[utils.validators.cep_validator],
                        verbose_name="CEP",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[utils.validators.cpf_validator],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Data de nascimento")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validators.phone_validator],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        validators=[utils.validators.cep_validator],
                        verbose_name="CEP",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudante",
                "verbose_name_plural": "Estudantes",
            },
        ),
        migrations.CreateModel(
            name="Suspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motivo")),
                (
                    "start_date",
                    models.DateField(
                        default=utils.date.get_today, verbose_name="Data de início"
                    ),
                ),
                ("end_date", models.DateField(verbose_name="Data de término")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suspensão",
                "verbose_name_plural": "Suspensões",
            },
        ),
        migrations.CreateModel(
            name="Tuition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de vencimento")),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("OVERDUE", "Atrasado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("reference_month", models.DateField(verbose_name="Mês de referência")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensalidade",
                "verbose_name_plural": "Mensalidades",
            },
        ),
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motivo")),
                (
                    "date",
                    models.DateField(default=utils.date.get_today, verbose_name="Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertência",
                "verbose_name_plural": "Advertências",
            },
        ),
    ]
