# Generated by Django 5.1.7 on 2025-11-11 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
                related_name="guardian_profile",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="students.guardian",
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professors",
                to="academics.subject",
                verbose_name="Disciplina",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
                related_name="professor_profile",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.group",
                verbose_name="Turma",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
                related_name="student_profile",
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guardians",
                to="students.student",
                verbose_name="Estudante",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="students.student",
                verbose_name="Estudante",
            ),
        ),
        migrations.AddField(
            model_name="suspension",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Emitido por",
            ),
        ),
        migrations.AddField(
            model_name="suspension",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suspensions",
                to="students.student",
                verbose_name="Estudante",
            ),
        ),
        migrations.AddField(
            model_name="tuition",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tuitions",
                to="students.student",
                verbose_name="Estudante",
            ),
        ),
        migrations.AddField(
            model_name="warning",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Emitido por",
            ),
        ),
        migrations.AddField(
            model_name="warning",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warnings",
                to="students.student",
                verbose_name="Estudante",
            ),
        ),
    ]
