# Generated by Django 5.1.7 on 2025-06-14 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_contract_created_at_alter_grade_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 13, 57, 8, 241203), editable=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 13, 57, 8, 242103), editable=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 13, 57, 8, 240685), editable=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 13, 57, 8, 242670), editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 13, 57, 8, 239890), editable=False),
        ),
    ]
