# Generated by Django 5.1.7 on 2025-08-25 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_alter_contract_created_at_alter_grade_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 883400), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 884049), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 882686), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 884703), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 881916), editable=False
            ),
        ),
    ]
