import HeaderButton from "./components/HeaderButton";

export default function Header() {
	return (
		<div className="header-vertical">
			<ul>
				<li>
					<HeaderButton
						url="/"
						icon="/home.svg"
						mensage="Início"
						alt="Home"
					/>
				</li>
				<li>
					<HeaderButton
						url="/students"
						icon="/student.svg"
						mensage="Estudantes"
						alt="Students"
					/>
				</li>
				<li>
					<HeaderButton
						url="/professors"
						icon="/teacher.svg"
						mensage="Professores"
						alt="Professors"
					/>
				</li>
				<li>
					<HeaderButton
						url="/subjects"
						icon="/gear.svg"
						mensage="Matérias"
						alt="Subjects"
					/>
				</li>
				<li>
					<HeaderButton
						url="/itineraries"
						icon="/calendar.svg"
						mensage="Itinerários"
						alt="Itineraries"
					/>
				</li>
				<li>
					<HeaderButton
						url="/groups"
						icon="/home.svg"
						mensage="Turmas"
						alt="Groups"
					/>
				</li>
				<li>
					<HeaderButton
						url="/lessons"
						icon="/calendar.svg"
						mensage="Horários"
						alt="Lessons"
					/>
				</li>
				<li>
					<HeaderButton
						url="/events"
						icon="/calendar.svg"
						mensage="Eventos"
						alt="Events"
					/>
				</li>
				<li>
					<HeaderButton
						url="/agenda"
						icon="/agenda.svg"
						mensage="Agenda"
						alt="Agenda"
					/>
				</li>
			</ul>
		</div>
	);
}
