# Generated by Django 5.1.7 on 2025-06-13 21:28

import datetime
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 28, 16, 457041), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, unique=True)),
                ('short_name', models.CharField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 28, 16, 455467), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, unique=True)),
                ('short_name', models.CharField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 28, 16, 455086), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name="Professor's full name")),
                ('phone_number', models.CharField(max_length=15, validators=[utils.validators.phone_validator], verbose_name="Professor's phone number (XX) 9XXXX-XXXX")),
                ('email', models.EmailField(max_length=100, verbose_name="Professor's email")),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[utils.validators.cpf_validator], verbose_name="Professor's CPF")),
                ('birthday', models.DateField(max_length=10)),
                ('address', models.CharField(max_length=100, validators=[utils.validators.cep_validator])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 28, 16, 456023), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 28, 16, 457464), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 28, 16, 456575), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, unique=True)),
                ('short_name', models.CharField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 6, 13, 18, 28, 16, 454694), editable=False)),
            ],
        ),
    ]
