# Generated by Django 5.1.7 on 2025-11-11 08:15

import django.db.models.deletion
import django.utils.timezone
import utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="Nome"),
                ),
                (
                    "author",
                    models.CharField(max_length=100, null=True, verbose_name="Autor"),
                ),
                (
                    "summary",
                    models.TextField(max_length=200, null=True, verbose_name="Resumo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Local"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=utils.date.get_today, verbose_name="Data de início"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=utils.date.get_today,
                        null=True,
                        verbose_name="Data de término",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de início"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de término"
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=False, verbose_name="Permitir inscrição"
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Máximo de participantes"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de inscrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição em Evento",
                "verbose_name_plural": "Inscrições em Eventos",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("GRADE", "Nota"),
                            ("ABSENCE", "Falta"),
                            ("WARNING", "Advertência"),
                            ("SUSPENSION", "Suspensão"),
                            ("EVENT", "Evento"),
                            ("ASSIGNMENT", "Trabalho"),
                            ("EXAM", "Prova"),
                            ("PAYMENT", "Pagamento"),
                            ("GENERAL", "Geral"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("read", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Sala de aula"),
                            ("LABORATORY", "Laboratório"),
                            ("AUDITORIUM", "Auditório"),
                            ("GYM", "Ginásio"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("capacity", models.IntegerField(verbose_name="Capacidade")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
            },
        ),
        migrations.CreateModel(
            name="RoomReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(max_length=200, verbose_name="Finalidade"),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("start_time", models.TimeField(verbose_name="Hora de início")),
                ("end_time", models.TimeField(verbose_name="Hora de término")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de Sala",
                "verbose_name_plural": "Reservas de Salas",
            },
        ),
        migrations.CreateModel(
            name="SchoolRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(null=True, verbose_name="Descrição")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Escolar",
                "verbose_name_plural": "Registros Escolares",
            },
        ),
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Hora")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agenda_item",
                        to="academics.subject",
                        verbose_name="Matéria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Agenda",
                "verbose_name_plural": "Itens da Agenda",
                "ordering": ["date", "time"],
            },
        ),
    ]
