# Generated by Django 5.1.7 on 2025-11-11 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinatário",
            ),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="reserved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_reservations",
                to="students.professor",
                verbose_name="Reservado por",
            ),
        ),
        migrations.AddField(
            model_name="roomreservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="school.room",
                verbose_name="Sala",
            ),
        ),
        migrations.AddField(
            model_name="schoolrecord",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_record",
                to="students.student",
                verbose_name="Estudante",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("event", "student")},
        ),
    ]
