# Generated by Django 5.1.7 on 2025-06-14 17:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_book_created_at_alter_group_created_at_and_more'),
        ('students', '0003_alter_contract_created_at_alter_grade_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 17, 980947), editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alugated_book', to='students.student', verbose_name="Tenant's name"),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 17, 978949), editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='school.itinerary', verbose_name='Itinerário da turma'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 17, 978397), editable=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 17, 979671), editable=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor', to='school.subject', verbose_name="Professor's Subject"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 17, 981530), editable=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='school.professor', verbose_name="Professor's name"),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 17, 980338), editable=False),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_record', to='students.student', verbose_name="Student's name"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 14, 2, 17, 977889), editable=False),
        ),
    ]
