# Generated by Django 5.1.7 on 2025-06-15 17:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_book_created_at_alter_itinerary_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='school.group', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 470908), editable=False),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 468908), editable=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 471452), editable=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')], null=True, verbose_name='Dia da semana (0=Segunda, 6=Domingo)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True, verbose_name='Horário (1° a 6°)'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 469923), editable=False),
        ),
        migrations.AlterField(
            model_name='schoolrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 470414), editable=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 14, 32, 43, 468478), editable=False),
        ),
    ]
