# Generated by Django 5.1.7 on 2025-08-25 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0015_alter_book_created_at_alter_itinerary_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 879998), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 878309), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 880676), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 879014), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="schoolrecord",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 879544), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 25, 14, 3, 0, 877980), editable=False
            ),
        ),
    ]
