name: Publish

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: ["master"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate .env files
        run: |
          cat ./api/.env.example > ./api/.env
          cat ./app/.env.example > ./app/.env
          cat ./db/.env.example > ./db/.env
          cat ./proxy/.env.example > ./proxy/.env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Executing publish script
        run: bash ./scripts/publish.sh
